
output: avr_client_functions.c avr_client_serial.c avr_client_shell.c shell.c error.c main.c
	gcc webserver.c avr_client_functions.c avr_client_serial.c avr_client_shell.c shell.c error.c main.c -o main -lwebsockets -lbluetooth
